# https://devenv.sh/integrations/github-actions
name: Test
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      # permissions required for nix caching to work properly
      id-token: write
      contents: read
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v15
        with:
          name: devenv

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
        shell: bash -e {0}

      - name: Cache turbo build
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:unit
      - run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            apps/*/test-results
